env:
  global:
    - TERM=dumb
    - GROOVY_TURN_OFF_JAVA_WARNINGS=true

language: java

dist: trusty

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode9.2
    - os: windows
      language: shell
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - chmod +x ./scripts/travis-ci/clean-tests.sh
  - ./scripts/travis-ci/clean-tests.sh

script:
  - chmod +x  ./scripts/travis-ci/run-tests.sh
  - ./scripts/travis-ci/run-tests.sh

branches:
  only:
    - master